micronaut:
application:
  name: MicronautCrud

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/micronaut`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:manager}
    driverClassName: com.mysql.cj.jdbc.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect